// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcREdxWGktDmfR1ss94bx3ssb7mPc9hCU',
    appId: '1:46917976454:web:52d1797490857236146c07',
    messagingSenderId: '46917976454',
    projectId: 'trackin-df4d8',
    authDomain: 'trackin-df4d8.firebaseapp.com',
    storageBucket: 'trackin-df4d8.firebasestorage.app',
    measurementId: 'G-CB4FBZLD66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJX9V5mTobnLzHNtuX56YOLLstx1NV4z0',
    appId: '1:46917976454:android:811802672af31706146c07',
    messagingSenderId: '46917976454',
    projectId: 'trackin-df4d8',
    storageBucket: 'trackin-df4d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS4ExPkfhTqF4I1echTt-CEzvtFPybTp4',
    appId: '1:46917976454:ios:4a67b51f56d87c73146c07',
    messagingSenderId: '46917976454',
    projectId: 'trackin-df4d8',
    storageBucket: 'trackin-df4d8.firebasestorage.app',
    iosBundleId: 'com.example.trackin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS4ExPkfhTqF4I1echTt-CEzvtFPybTp4',
    appId: '1:46917976454:ios:4a67b51f56d87c73146c07',
    messagingSenderId: '46917976454',
    projectId: 'trackin-df4d8',
    storageBucket: 'trackin-df4d8.firebasestorage.app',
    iosBundleId: 'com.example.trackin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcREdxWGktDmfR1ss94bx3ssb7mPc9hCU',
    appId: '1:46917976454:web:86df5d9bb62701d0146c07',
    messagingSenderId: '46917976454',
    projectId: 'trackin-df4d8',
    authDomain: 'trackin-df4d8.firebaseapp.com',
    storageBucket: 'trackin-df4d8.firebasestorage.app',
    measurementId: 'G-Z6HWSY8BY8',
  );
}
